# GAN Training Configuration

model:
  embedding_dim: 704
  num_attributes: 4
  generator:
    hidden_dim: 512
    num_residual_blocks: 6
    dropout: 0.1
  discriminator:
    hidden_dim: 512
    dropout: 0.3

training:
  epochs: 100
  batch_size: 64
  lr_generator: 0.0001
  lr_discriminator: 0.0004
  d_steps_per_g_step: 2
  
loss_weights:
  lambda_attr: 1.0
  lambda_dist: 1.0
  lambda_smooth: 0.1

curriculum:
  phase1:
    epochs: 20
    lambda_attr: 0.0
    lambda_dist: 1.0
    lambda_smooth: 0.0
    delta_range: [-0.3, 0.3]
    lambda_anon_range: [0.0, 0.3]
  
  phase2:
    epochs: 30
    lambda_attr: 0.5
    lambda_dist: 1.0
    lambda_smooth: 0.0
    delta_range: [-0.6, 0.6]
    lambda_anon_range: [0.0, 0.6]
  
  phase3:
    epochs: 50
    lambda_attr: 1.0
    lambda_dist: 1.0
    lambda_smooth: 0.1
    delta_range: [-1.0, 1.0]
    lambda_anon_range: [0.0, 1.0]

data:
  embeddings_path: "data/train_embeddings.pt"
  metadata_path: "/data/waris/data/Voxceleb/voxceleb1/final_metadata_train.csv"
  num_workers: 4
